### PR TITLE
Upgrade to imgui 0.7

### PR DESCRIPTION
**Pull request by repi**
Upgrade to the latest imgui 0.7 version that was just released

### CODE REVIEW

**Comment by aclysma** [comment]
Looks like a log file was unintentionally added. (I wouldn't object to adding *.log to the .gitignore)

I don't expect the demo project compiles with this change. However I can take care of that later. (I plan to use `rafx` instead of `skulpin` - it will be much lighter on dependencies. Also the skia crate doesn't work on apple silicon)

**Comment by repi** [comment]
Oops odd, will remove the log file

**Comment by aclysma** [comment]
Published as 0.8.0 - and the rewritten demo should make testing updates much easier :)

**Comment by repi** [comment]
thanks!

**Pull request merged**
